name: Manual Dependabot

on:
  workflow_dispatch:

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Trigger Dependabot
      uses: dependabot/fetch-metadata@v1.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
